### ISSUE TITLE
Continuous printing in the sample C program

### ISSUE THREAD

**Issue by VarLad** [feenkcom/libwinit#5]
Running https://github.com/rust-windowing/winit/blob/master/examples/window.rs example from Rust only prints to the terminal when an event happens in the window.
Compared to that, if I add a `printf("Something\n");` at the top of `process_event` function in the example, it prints continuously. 
I don't know if thats the correct behavior or not. But perhaps this might be related to the performance hit reported in https://github.com/feenkcom/libwinit/issues/4

**Comment by syrel** [comment]
Indeed. For our purposes we had to wake up an even loop a bit more frequently.
The new methods as mentioned in https://github.com/feenkcom/libwinit/issues/4 don't consume cpu any more :)
Btw, if an app requests window redraw from within `MainEventsCleared` event then Winit will end up in a never ending loop of events :) Watch out
