### ISSUE TITLE
the example does not compile with libraries from releases

### ISSUE THREAD

**Issue by littleangryork** [feenkcom/libwinit#8]
I just decided to download the files from the releases and compile an example. This gave errors: 

![изображение](https://user-images.githubusercontent.com/96008773/223628842-24c27851-f68b-498a-a921-6220068efca7.png)

I looked at the early issues where the libBoxer library was missing, I believe it is exactly the same here.

Please make a guide step by step for the small and stupid (for me)

**Comment by VarLad** [comment]
@littleangryork The cbindgen.toml file might need to be updated. 
Lets follow this on https://github.com/feenkcom/libwinit/issues/9 and close this issue?
